# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  
  # Ejecutar automáticamente cada día 2 del mes a las 10:00 UTC
  schedule:
    - cron: '0 10 2 * *'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checks-out repository and submodules
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.DEPLOYSECRET }}
          submodules: 'recursive'
          
      # Step 2: Install Hugo
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.0'  # your Hugo version here
        
      # Step 3: Build and deploy with this action
      - name: Build Hugo site 🔧 and deploy 🚀
        uses: aormsby/hugo-deploy-to-pages@v1.2-beta
        with:
          hugo_publish_directory: 'public'
          source_branch: 'master'
          deploy_branch: 'master'
          commit_message: 'Automatic build and deploy.'
          submodule_branch: 'master'
          hugo_build_options: '--theme meghna-hugo'
          
